# Functions for initializing the input data.

#' Input Initializers
#'
#' These methods deal with converting the input coordinates or distances
#' into the structures required by different embedding methods. For instance,
#' probability-based embedding methods require the construction of a probability
#' matrix from the input distances.
#'
#' @seealso Input initializers should be passed to the
#' \code{init_inp} parameter of embedding functions such as
#' \code{\link{embed_prob}} or \code{\link{embed_dist}}.
#'
#' @examples
#'
#' \dontrun{
#' # initializer that uses bisection search to create input probability
#' # distribution with a perplexity of 50
#' # pass result to init_inp parameter of an embedding function
#' embed_prob(method = tsne(), init_inp = inp_from_perp(perplexity = 50), ...)
#' }
#' @keywords internal
#' @name input_initializers
#' @family sneer input initializers
NULL

#' Input Probability Initialization By Bisection Search on Perplexity
#'
#' An initialization method for creating input probabilities.
#'
#' Function to generate a row probability matrix by optimizing a one-parameter
#' weighting function. This is used to create input probabilities from the
#' input distances, such that each row of the matrix is a probability
#' distribution with the specified perplexity.
#'
#' This is the method described in the original SNE paper, and few methods
#' deviate very strongly from it, although they may do further processing
#' on the resulting probability matrix. For example, SSNE and t-SNE convert
#' this matrix into a single joint probability distribution.
#'
#' @section Exported data:
#' Data generated by this initializer can be exported from the embedding
#' function by passing \code{"inp"} to the embedding function's
#' \code{export} list parameter. The return value of the embedding function is a
#' list, which will contain a member called \code{"inp"}. In turn, this is a list
#' containing the input data. If this initializer is used, the list will contain
#' the following data:
#' \describe{
#'  \item{\code{pm}}{Input probabilities.}
#'  \item{\code{beta}}{Input weighting parameters that produced the
#'     probabilities. Only provided if \code{keep_all_results} is \code{TRUE}.}
#' }
#'
#' @param perplexity Target perplexity value for the probability distributions.
#' @param input_weight_fn Weighting function for distances. It should have the
#'   signature \code{input_weight_fn(d2m, beta)}, where \code{d2m} is a matrix
#'   of squared distances and \code{beta} is a real-valued scalar parameter
#'   which will be varied as part of the search to produce the desired
#'   \code{perplexity}. The function should return a matrix of weights
#'   corresponding to the transformed squared distances passed in as arguments.
#' @param keep_all_results If \code{true} then the list returned by the callback
#'   will also contain a vector of \code{beta} parameters that generated the
#'   probability matrix. Otherwise, only the probability matrix is returned.
#' @param verbose If \code{TRUE} display messages about progress of
#'   initialization.
#' @return Input initializer for use by an embedding function.
#' @seealso \code{\link{embed_prob}} and \code{\link{embed_dist}} for more
#'   information on exporting initializer data.
#' @examples
#' # Set target perplexity of each probability distribution to 30
#' inp_from_perp(perplexity = 30)
#'
#' # Set target perplexity of each probability distribution to 30 but use
#' # a different weighting function.
#' inp_from_perp(perplexity = 30, input_weight_fn = sqrt_exp_weight)
#'
#' # Perplexity of 50, and keep the values of the exponential parameter for
#' # later processing or reporting.
#' inp_from_perp(perplexity = 50, keep_all_results = TRUE)
#'
#' \dontrun{
#' # Should be passed to the init_inp argument of an embedding function
#' # To access input data, use the export parameter to export the "inp"
#' # input data.
#' embed_prob(init_inp = inp_from_perp(perplexity = 30,
#'  input_weight_fn = exp_weight), export = c("inp"))
#' }
#' @family sneer input initializers
#' @export
inp_from_perp <- function(perplexity = 30,
                             input_weight_fn = exp_weight,
                             keep_all_results = FALSE,
                             verbose = TRUE) {
  inp_prob(
    function(inp) {
      d_to_p_result <- d_to_p_perp_bisect(inp$dm, perplexity = perplexity,
                                          weight_fn = input_weight_fn,
                                          verbose = verbose)

      if (keep_all_results) {
        for (name in names(d_to_p_result)) {
          inp[[name]] <- d_to_p_result[[name]]
        }
      }
      else {
        inp$pm <- d_to_p_result$pm
      }
      flush.console()
      inp
    }
  )
}

#' Wrap Input Probability Initializer
#'
#' This function takes an input initializer which creates a probability, and
#' wraps it so that the correct handling of the probability matrix can be
#' carried out when it is invoked.
#'
#' @param input_initializer Input initializer which creates a probabilty.
#' @return Wrapped initializer with the correct signature for use by an
#'  embedding function.
#' @seealso \code{\link{probability_matrices}} describe the type of probability
#'   matrix used by sneer.
inp_prob <- function(input_initializer) {
  function(inp, method) {
    inp <- input_initializer(inp)
    inp$pm <- handle_prob(inp$pm, method)
    inp
  }
}
